function BusData()
cellInfo = {...
    {...
    'PendulumInBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'torque', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    }...
    {...
    'PendulumOutBus', ...
    '', ...
    '', ...
    'Auto', ...
    '-1', {...
    {'shoulder_position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'shoulder_velocity', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'ellbow_position', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    {'ellbow_velocity', 1, 'double', -1, 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
    }};
Simulink.Bus.cellToObject(cellInfo);
end